version: "3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - portainer-docker-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: --admin-password '$$2y$$05$$55oFixP58U6/8oaxX13nZOS82H.PuXUQvvEV/yyO6jaFg/8pRQnGK'
  
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - portainer-docker-data:/data

volumes:
  portainer-docker-data: